trainingdbt:
  outputs:
    dev:
      dbname: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      pass: admin
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
